spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-core-domain-datasource.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
