version: '3'
services:
  mysql:
    container_name: core-mysql
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=UTC
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
